[package]
name = "immutability"
version = "0.1.0"
authors = ["yaowenqiang <yaowenqiang111@163.com>"]
edition = "2018"

[dependencies]
rand = "0.4"
git2 = "0.9.2"

[dependencies.some_crate]
path="src/some_crate"
